### ISSUE TITLE
Naglering - not giving stamina and defense

### ISSUE THREAD

**Issue by Avlli** [LightsHope/issues#1123]
Hello guys,

I have noticed that Naglering is not giving stamina and defense. 
I think 3 arcane dmg is working as i remember from instance, but for sure i will recheck that one.

With Naglering:
![image](https://user-images.githubusercontent.com/32401344/49213425-955f7200-f3c4-11e8-8b53-7cd4f852eede.png)
![image](https://user-images.githubusercontent.com/32401344/49213448-a314f780-f3c4-11e8-90eb-b02e55e16f68.png)

Without:
![image](https://user-images.githubusercontent.com/32401344/49213460-ac05c900-f3c4-11e8-9973-581dd225ff01.png)
![image](https://user-images.githubusercontent.com/32401344/49213475-b1fbaa00-f3c4-11e8-8eb7-1a2be8321916.png)

**Comment by Shivsproket** [comment]
This item, a long with many other items, is changed during later patches. It's part of an effort to maintain the game in a blizzlike state. What you are seeing is the patch 1.10 version of Naglering, but currently Northdale is on patch 1.6. The item stats are displayed based on what is in your WDB folder, and it seems like your WDB folder is on patch 1.10 at least. It's a common issue that happens if you swap from server to server with different patches such as from Lightbringer to Northdale.

To see the correct item stats you should go delete your WDB folder (don't worry it won't mess anything up), then when you connect to the server your client should automatically fetch the correct version. If you want to ensure that your WDB is always up to date then you should delete it after every new patch is deployed on the server.

**Comment by Avlli** [comment]
Thx you are right :)
