### ISSUE TITLE
Some Addons fail to load/Addon button dissapears since realm migration

### ISSUE THREAD

**Issue by towneh** [LightsHope/issues#142]
Best way to describe this is with a video link: https://www.youtube.com/watch?v=GcY1LP0SyeM

This has been happening on Darrowshire since the server migration was completed over the weekend and had affected everyone in our raid last night.

Some addons fail to load and the addon button is not reachable on the character screen after initially logging in. You have to change realms before this reappears.

**Comment by theloras** [comment]
i just noticed this myself lol

**Comment by theloras** [comment]
Ayeri - Today at 12:46 PM
apparently if you switch to LB server
and come back
it should be up
someone said that to me

**Comment by spachib** [comment]
+1 Also experienced the missing addon button. The change server workaround works for me

**Comment by Byste** [comment]
Also having these issues.

Addons are getting messed up, losing auction house data, gatherer data, luna frames are buggy with no text/pictures, probably more things messed up since the server move -- and this happens on every login.

Also having the missing addon button, but like everyone else, switching servers to Lightbringer (not Anathema) brings the button back. I have to do it every login.

**Comment by Starfallen1** [comment]
I also have the same issue, have tried multiple clients, completely removing my wtf folder, changing my config file, new addon folders, nothing solves the problem for me besides switching to lightbringer every time I log in.
