### ISSUE TITLE
Twin Emperors combat bug

### ISSUE THREAD

**Issue by berillis** [LightsHope/issues#62]
If Twin Emperors are killed with any Anubisath Warder alive, the whole raid will be in combat with no means to get the combat off (without GM assistance).

<GM> Nylth said that all the Warders must be killed before Twin Emperors, otherwise they will aggro when Twin Emperors are pulled and most likely will wipe the raid.

Some of our raiders are saying that you could skip 1-2 of them in retail with no problems.

Either way, the current implementation is not correct.

**Comment by Cabro** [comment]
I can confirm that the Warders shouldn't be linked with the Twins, combat-wise. You could skip them on retail.

**Comment by GuybrushGit** [comment]
Multiple comments from much later patches say they agro: http://www.wowhead.com/npc=15276/emperor-veklor

**Comment by Cabro** [comment]
Yes because there was 1 that was patrolling all the way to the door, and it was aggroing because body pull, not because boss was pulled. Also the comments are from patch 5+. I honestly remember you could skip them and only the one that was patrolling would be bodypulled because superhuge aggro range.
Chances are they changed it so ppl stop soloing AQ40?
You need some proof from vanilla (that Anubisaths would aggro with boss) afaik and all these bug reports are.
