### ISSUE TITLE
[835] Large Rope Net

### ISSUE THREAD

**Issue by Keftenk** [LightsHope/issues#717]
Large Rope Net isn't supposed to be in the game until Patch 1.11.

http://wowwiki.wikia.com/wiki/Large_Rope_Net

**Comment by Gamemechanicwow** [comment]
Mentioned in undocumented patchnotes 1.7:
http://blue.cardplace.com/cache/wow-general/4881021.htm

July 2005:
http://wow.allakhazam.com/forum.html?forum=243&mid=1120681464125961960

January 2005:
https://web.archive.org/web/20050118163516/http://wow.allakhazam.com/db/item.html?witem=835

Large rope net was ingame at very early stages. Got removed later - and changing already collected drops to BoP.

The real bug is that the nets are currently BoP.

**Comment by ratkosrb** [comment]
You can tell from the item ID alone that this was among the earliest items ever added to the game. It was first seen by Allakhazam on 2004-03-29 which is waaaay before the release of the game.
https://web.archive.org/web/20050527200833/http://wow.allakhazam.com:80/db/itemhistory.html?witem=835

As @stesve mentioned the real bug here is that it should not be BoP in the beginning, and was removed from loot tables in patch 1.7.

Fixed here https://github.com/lh-server/core/pull/199
