### ISSUE TITLE
Augustus the Touched is missing one of his texts

### ISSUE THREAD

**Issue by lazermon** [LightsHope/issues#739]
Current behaviour:
The quest appears as lvl 10: https://i.imgur.com/COHrgEn.png
However, it is correctly marked as lvl 55 when acquired: https://i.imgur.com/uJvmTKF.png
and rewards 1400 experience at lvl 56: https://i.imgur.com/XkFmvsH.png

Correct Behaviour:
It should be a lvl 55 quest that rewards 2800 XP:
https://web.archive.org/web/20070102202858/http://thottbot.com/?f=q&type=I&zones=59

He also seems to not be /yelling this line: "Commerce, I crave it!"

By Liberace on 01/01/2011 (Patch 3.1.3)
I was finally out in EPL again the other day and he yelled one I hadn't heard before. It was along the lines of "Commerce! I crave it!" Brilliant!
Last edited by Liberace on 01/02/2011 (Patch 3.1.3)

(https://classicdb.ch/?npc=12384#comments)

**Comment by ratkosrb** [comment]
First part of this issue is invalid. The quest already requires level 50 not 10. Go and try to pick it up on a level 10 character and you'll see that you cannot. You must be using some crap addon that comes with wrong data from a stock mangos database.

Second issue fixed here:
https://github.com/lh-server/core/pull/199

**Comment by lazermon** [comment]
When you speak of the second issue, are you referring to the missing line of text, or the amount of experience? I assume you mean the missing line of text (which is nice to see added), it would be nice to see the amount of experience corrected as well!

Thank you for your work!
