### ISSUE TITLE
Auto attack and spellcasting

### ISSUE THREAD

**Issue by Sarmatius** [LightsHope/issues#855]
Northdale PvP
Observed: Casting Lightning Bolt or Wrath while auto attacking resets attack leading to no white hit.
Intended: Casting an offensive spell with cast time, while the time left until next white hit is shorter than cast, makes the white hit go off immediately on spell cast finish. (If the spellcast finished before the white hit was supposed to go off, the autoattack sequence would reset as it is the case everytime on live server)

While playing on Nostalrius and Elysium as a Shaman or Druid, it was a standard way of doing damage - autoattacking between Lightning Bolt casts. Casting a Healing Spell or Chain Lightning would reset autoattack sequence though, leading to no white hit. It also worked as a Mage with Fireball and Frostbolt.

It didn't work when casting healing spells or chain lightning - it resetted attack timer, but with offensive spells it should work.

**Comment by Cabro** [comment]
Pretty sure it was bugged there.

**Comment by Sarmatius** [comment]
https://www.youtube.com/watch?v=pvf8AXySB38

This video shows a shaman using this mechanic on nostalrius

**Comment by ratkosrb** [comment]
So because it was bugged on Nostalrius, we should bug it here as well? Infallible logic.

**Comment by Sarmatius** [comment]
How was it bugged? It was working as intended.. it is the base of my playstyle as a shaman and druid come on.. 
You say it was bugged on all vanilla servers except this exceptional one? /clap

**Comment by ratkosrb** [comment]
```
How was it bugged?
```
The bug was that your swing timer was not being reset at the end of the cast. This is a stock mangos bug. In fact they intended to reset it at the end of the cast, but put the reset in the wrong function. It was being reset when the spell missile (in this case the lightning bolt itself) hit the target, which is obviously not what was intended.

```
it is the base of my playstyle as a shaman and druid
```
Then you based your play style on a bug.

```
You say it was bugged on all vanilla servers except this exceptional one
```
Yes it was. I'll be anxiously awaiting your post on blizzard forums once official classic is released, arguing how they should reproduce private servers bugs to suit your play style.
