### ISSUE TITLE
CastSpellByName not working correctly

### ISSUE THREAD

**Issue by ellii** [LightsHope/issues#902]
hello,

I'm creating addon and I find a strange behavior that `CastSpellByName("Cooking")` is not working from addon. I can type `/script CastSpellByName("Cooking")` from macro and it's working. 

It cannot be used from Addon for normal spells but based on [This](http://classic-wow.wikia.com/wiki/API_CastSpellByName) I think it should be possible to call this function for opening Crafting Window.

From the same [Page](http://classic-wow.wikia.com/wiki/World_of_Warcraft_API) `DoTradeSkill` seems protected but it shouldn't be.

**Comment by Cabro** [comment]
It's a protected function, it requires a physical input (keyboard/mouse) to fire.

**Comment by ellii** [comment]
Is there any source? From what i found is that you can open trade skill windows. And this function is protected since patch 2.0.1. so on this patch it should work.

**Comment by Cabro** [comment]
Not since 2.0.1, but sometime in vanilla. Maybe the input requirement was before whatever you found (probably it's not about the "protected" attribute).
Found it, it's 1.10. And they don't do spell progression. Besides, this would make room for some huge abuses, which is why blizzard made it like this. Good luck with changing it, though.

**Comment by bladezLH** [comment]
The API is client controlled and we only support 1.12.x clients.
