### ISSUE TITLE
Game Crashes everytime entering Dun Morogh

### ISSUE THREAD

**Issue by brosecuervo7** [LightsHope/issues#903]
The game crashes every time I enter the zone "Dun Morogh" with a character. It says assertion failed... I have tried with two different characters and got the same outcome. All other characters can enter zones fine.... Characters are Icybawls and Icypoon... Did a full reinstallation. Restarted computer... Still no luck.

**Comment by Godmatik** [comment]
Your only solution is to open a GM ticket on another character and have him teleport you somewhere else.

The MAC client has a corrupted file for Dun Morogh. Nothing can be done until someone fixes it and releases a new MAC client (if ever). For now, just avoid the area.

**Comment by Falshaek** [comment]
I found a fix
Same thing happened to me, on my way to kharanos, turn right to go passed rumbleshot quest and boom, crashed, many times and many alts. Instead of taking that right at the bottom of the hill to go passed rumbleshot, keep going straight, down the hill passed the large cats, through the ravine where the elite is, think its lvl 10, then all the way around back to kharanos. It works, I'm lvl 7 now and doing quests around kharanos. Do not do the rumbleshot quest, that will bring you to the glitched spot, it might crash your game, I did not risk it, you should not either. Avoid the area, getting the frostmane hide for the quest is fine to do and everywhere in kharanos is ok too, just seems to be right by rumbleshot. Thank you, good luck.
